name: Release

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    name: Release Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: build
      working-directory: dev/lobster
      run: msbuild.exe lobster.sln /p:Configuration=Release /p:Platform=x64
    - name: test
      run: bin/lobster.exe tests/unittest.lobster
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Windows Release ${{ github.event.release.tag_name }}
        files: |
          bin/*
          data/*
          docs/*
          modules/*
          samples/*
          tests/*
          README.md
